# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('English_word', models.CharField(max_length=30)),
                ('hands_used', models.CharField(max_length=30)),
                ('handshape', models.CharField(max_length=30)),
                ('hand_motion', models.CharField(max_length=30)),
                ('hand_movement', models.CharField(max_length=30)),
                ('orientation', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('expression', models.CharField(max_length=30)),
            ],
        ),
    ]
